health/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.health),
    path('<int:id>',views.detailh,name='detailh')
    
]

home/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.home),
    path('<int:id>',views.detailhome,name='detailshome')
]

news/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from . import settings
from django.conf.urls.static import static 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ck_uploads/',include('ckeditor_uploader.urls')),
    path('politics/',include('politics.urls',)),
    path('',include('home.urls')),
    path('home/',include('home.urls')),
    path('health/',include('health.urls')),
    path('accounts/',include('accounts.urls')),
    path('user/',include('user.urls')),
    path('sports/',include('sports.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sports/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.sports),
    path('<int:id>',views.details,name='details')
    
]

health/models.py
from django.db import models

# Create your models here.
class content(models.Model):
    name=models.CharField(max_length=255)
    time=models.TimeField()
    image=models.ImageField(upload_to='health')
    def __str__(self):
    
       return self.name
    
    class Meta:
    
        verbose_name=' health' 
    
class Detailh(models.Model):
    id=models.IntegerField(primary_key=True)
    author = models.CharField(max_length=255)
    #author=models.CharField(max_length=255)
    name=models.ForeignKey(content, on_delete=models.CASCADE,related_name='names')
    time=models.TimeField()
    #image=models.ImageField(upload_to='details')
    image=models.ForeignKey(content, on_delete=models.CASCADE,related_name='images')
    content=models.TextField()
    
    
    # def __str__(self):
    
    #    return self.name
    
    # class Meta:
    
    #     verbose_name='detailh' 
    
        
    


    
#detailh = detailh.objects.get(id=1)

home/models.py
from django.db import models
#from accounts.models import User



class content(models.Model):
    
    
    #author=models.CharField(max_length=255)
    name=models.CharField(max_length=255)
    time=models.TimeField()
    image=models.ImageField(upload_to='home')
    
    def __str__(self):
    
       return self.name
    
    class Meta:
    
        verbose_name='home' 
        
        
    
class detailho(models.Model):
    id=models.AutoField(primary_key=True)
    

    author = models.CharField(max_length=255)
    #author=models.CharField(max_length=255)
    name=models.ForeignKey(content, on_delete=models.CASCADE,related_name='names')
    time=models.TimeField()
    
    image=models.ForeignKey(content, on_delete=models.CASCADE,related_name='images')
    contents=models.TextField() 
    
    
    def __str__(self):
    
       return self.name
    
    class Meta:
    
        verbose_name='detailhome' 
        
    
 

politics/models.py
from django.db import models

# Create your models here.
class content(models.Model):
    name=models.CharField(max_length=255)
    time=models.TimeField()
    image=models.ImageField(upload_to='politics')
    
       
    def __str__(self):
    
        return self.name
    
    class Meta:
    
        verbose_name='politics'
    
    
class detailp(models.Model):
    id=models.AutoField(primary_key=True)
    
    
    name=models.ForeignKey(content, on_delete=models.CASCADE,related_name='names')
    time=models.TimeField()
    
    image=models.ForeignKey(content, on_delete=models.CASCADE,related_name='images')
    author = models.CharField(max_length=255)
    contents=models.TextField()
    
    
  

sports/models.py
from django.db import models

# Create your models here.
class content(models.Model):
    name=models.CharField(max_length=255)
    time=models.TimeField()
    image=models.ImageField(upload_to='sports')
           
    def __str__(self):
    
        return self.name
    
    class Meta:
    
        verbose_name='sports'
    
    
class Details(models.Model):
  id=models.AutoField(primary_key=True)  ,
  author = models.CharField(max_length=255)
  
  name=models.ForeignKey(content, on_delete=models.CASCADE,related_name='names')
  time=models.TimeField()
    
  image=models.ForeignKey(content, on_delete=models.CASCADE,related_name='images')
  content=models.TextField()
    
    

user/models.py
from django.db import models
from health.models import content
from sports.models import content
from politics.models import content
from home.models import content
from accounts.models import User


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(content, on_delete=models.CASCADE)
    comment = models.TextField()
    
    

class like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(content, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'content')

health/views.py
from django.shortcuts import render
from django.http import HttpResponse
from health.models import content,Detailh


def health(request):
    health=content.objects.all()
    return render(request,'health.html',{'health':health})



def detailh(request,id):
    
    detailh_qs=Detailh.objects.filter(id=id)
    detailh=Detailh.objects.get(id=id)
    return render(request, 'detailh.html', {'detailh':detailh})
   

home/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from home.models import content,detailho


def home(request):
    home=content.objects.all()
    return render(request,'home.html',{'home':home} )


   
def detailhome(request,id):
    
    detailho_qs =detailho.objects.filter(id=id)
    #detailshome =get_object_or_404(detailho, id=id)

    detailshome=detailho.objects.get(id=id)
    return render(request,'details.html',{'detailshome':detailshome})

politics/views.py
from django.shortcuts import render
from django.http import HttpResponse
from politics.models import content,detailp


def politics(request):
    politics=content.objects.all()
    return render(request,'politics.html',{'politics':politics})



def get_detailp(request,id):
    detailp_qs=detailp.objects.filter(id=id)
    detailsp=detailp.objects.get(id=id)
    return render(request,'detailp.html',{'detailp':detailsp})
   

sports/views.py
from django.shortcuts import render
from django.http import HttpResponse
from sports.models import content,Details


def sports(request):
    sports=content.objects.all()
    return render(request,'sports.html',{'sports':sports})




def details(request,id):
    
    details_qs=Details.objects.filter(id=id)
    
    details=Details.objects.get(id=id)
    return render(request, 'detailsp.html', {'details':details})
   

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>      Enews  </title>

    <link href="{% static 'style.css' %}" rel="stylesheet"/>
    
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ENews</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="home">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="politics">Politics</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="health">Health</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="sports">Sports</a>
              </li>
             
            
            


              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {% if user.is_authenticated %} {{ request.user }} {% else %} User {% endif %}
                  
                </a>
                <ul class="dropdown-menu">
                  {% if user.is_authenticated %} 
                  <li> <a  class="dropdown-item" href="{% url 'comment' %}">comment <a/></li>
                    <li> <a  class="dropdown-item" href="{% url 'like' %}">Like <a/></li>
                      <li> <a  class="dropdown-item" href="{% url 'logout' %}">logout<a/></li>
                        {% else %}
                
                                    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#loginModal">Login</a></li>
                                    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#registerModal">Register</a></li>
                                  {% endif %}
                                  </ul>
                                </li>
                
                              </ul>
  
  
                              <form class="d-flex" role="search">
                                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success" type="submit">Search</button>
                              </form>
                            </div>
                          </div>
                        </nav>
                      </header>
                
                {% if not user.is_authenticated %}
                      <!-- Login Modal -->
                      <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h1 class="modal-title fs-5" id="loginModalLabel">User Login</h1>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              <form action="{% url 'login' %}" method="post">
                                {% csrf_token %}
                                <div class="mb-3">
                                  <label for="">username</label>
                                  <input type="text" class="form-control" name="un">
                                </div>
                                <div class="mb-3">
                                  <label for="">Password</label>
                                  <input type="password" class="form-control" name="pw">
                                </div>
                                <div class="mb-3">
                                  <input type="submit" class="btn btn-primary" value="Login">
                                </div>
                              </form>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>
                
                
                      <!-- Registration Modal -->
                      <div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h1 class="modal-title fs-5" id="registerModalLabel">User Registration</h1>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <class="modal-body">
                              <form action="{% url 'register' %}" method="post">
                                {% csrf_token %}
                                <div class="mb-3">
                                  <label for="">First Name</label>
                                  <input type="text" class="form-control" name="fn">
                                </div>
                                <div class="mb-3">
                                  <label for="">Last Name</label>
                                  <input type="text" class="form-control" name="ln">
                                </div>
                                <div class="mb-3">
                                  <label for="">Email</label>
                                  <input type="email" class="form-control" name="em">
                                </div>
                                <div class="mb-3">
                                  <label for="">Mobile</label>
                                  <input type="text" class="form-control" name="mb">
                                </div>
                                <div class="mb-3">
                                  <label for="">Address</label>
                                  <input type="text" class="form-control" name="ad">
                                </div>
                                <div class="mb-3">
                                  <label for="">username</label>
                                  <input type="text" class="form-control" name="un">
                                </div>
                                <div class="mb-3">
                                  <label for="">Password</label>
                                  <input type="password" class="form-control" name="pw">
                                </div>
                                <div class="mb-3">
                                  <input type="submit" class="btn btn-primary" value="Register">
                                </div>
                              </form>
                            
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>




              






  <div>
    <a class="navbar-brand" href="#">
      <img src="{% static 'images/logo.png' %}" alt="logo" id="logo"/>
    </a>
  </div>

{% endif %}





    
</head>
<body>
    {%block content %}




    {% endblock  %}


<div class="footer"> 
  <footer class="row" id="footer">
    <div class="col-md-4">
      <p class="text-light">All Right Reserved &copy; ENews.</p>
    </div>

    <div class="col-md-4">
      <h3 class="text-light">Quick Links</h3>

      <ul style="list-style: none; padding-left: 0;">
        <li><a class="text-light" href="/about/content/About">About</a></li>
        <li><a class="text-light" href="/about/content/Policies">Policies</a></li>
        <li><a class="text-light" href="/about/content/Contacts">Contacts</a></li>
      </ul>
    </div>

    <div class="col-md-4">
      <h4 class="text-light">Subscribe Us:</h4>
      <form action="">
        <input type="email" class="form" name="email" 
          placeholder="Your Email">
        <input type="submit" class="btn btn-info" value="Subscribe">
      </form>
    </div>
  </footer>
</div>

</body>
</html>

templates/detailh.html
{% extends 'health.html' %}

{% block title %}

<div class="col-12">
    <h2 class="text-center m-5">Health</h2>
  </div>

{% endblock%}





{% block content %}
<div class="health">
  
        <div class="news-article">
            

            <h2>{{ detailh.name }}</h2>
            
                <img src="media/{{ detailh.image }}" alt="{{detailh.name}}">
            
            <p>{{ detailh.content }}</p>
            <p>Published by {{ detailh.author }} on {{ detailh.time }}</p>
        </div>
 
</div>
  
{% endblock%}

templates/detailp.html
{% extends 'politics.html' %}







{% block content %}
<div class="politics">
    
        <div class="news-article">
          

            <h2>{{detailp.name}}</h2>
            
                <img src="{{detailp.image}}" alt="{{detailp.name}}">
            
            <p>{{ detailp.contents }}</p>
            <p>Published by {{ detailp.author }} on {{ detailp.time }}</p>
        </div>

</div>
  
{% endblock%}

templates/details.html
{% extends 'home.html' %}

{% block title %}


{% endblock%}





{% block content%}

<div class="home">
    
        <div class="news-article">
            <h2>{{ detailshome.name }}</h2>
           
                <img src="{{ detailshome.image.url }}" alt="{{ detailshome.name }}">
          
            <p>{{ detailshome.contents }}</p>
            <p>Published by {{ detailshome.author }} on {{ detailshome.time }}</p>
        </div>
   
</div>
  
{% endblock%}

templates/detailsp.html
{% extends 'sports.html' %}
{% block title%}


{% endblock%}

{% block content %}
<div class="sports">
    
    <div class="news-article">
        <h2>{{ details.name }}</h2>
       
            <img src="{{ details.image.url }}" alt="{{ details.name }}">
      
        <p>{{ details.content }}</p>
        <p>Published by {{ details.author }} on {{ details.time }}</p>
    </div>

</div>

{% endblock%}

templates/health.html
{% extends 'base.html' %}
{% load static %}


{% block title %}

<div class="col-12">
    <h2 class="text-center m-5">Health</h2>
  </div>
{% endblock  %}




{% block content %}

<section class="row" id="latest">
  {% for s in health %}

  <div class="col-lg-3 col-md-4">
    <div class="card">
      <img src="/media/{{s.image}}" class="card-img-top" alt="photo">
      <div class="card-body">
        <h5 class="card-title">{{s.name}}</h5>
        
        <p class="card-text">{{s.time}}</p>
        <a href="{{s.id}}" class="btn btn-primary">Click Here
          <i class="bi bi-cart"></i>
        </a>
        <button class="btn btn-outline-primary like-btn" data-article-id="{{ article.id }}">
          <i class="far fa-heart"></i>
          <span class="like-count">{{ article.like_set.count }}</span>
      </button>
      
    
      <script src="script.js">
      </script>
       
      </div>
    </div>
  </div>


{% endfor %}
{% endblock  %}

templates/home.html
{% extends 'base.html' %}

{% load static %}



{% block content%}

<section class="row" id="latest">

  <div class="col-12">
    <h2 class="text-center m-5">Latest News</h2>
  </div>

  {% for p in home %}

  <div class="col-lg-3 col-md-4">
    <div class="card">
      <img src="/media/{{p.image}}" class="card-img-top" alt="photo">
      <div class="card-body">
        <h5 class="card-title">{{p.name}}</h5>
        
        <p class="card-text">{{p.time}}</p>
        <a href="{{p.id}}" class="btn btn-primary">Click Here
          <i class="bi bi-cart"></i>
        </a>
       
      <a href="#" class="btn btn-danger">
        <i class="bi bi-heart"></i>
      </a>

      

    
      <script src="script.js">
      </script>
      
      </div>
    </div>
  </div>


{% endfor %}

{% endblock  %}

templates/politics.html
{% extends 'base.html' %}
{% load static %}


{% block title %}

<div class="col-12">
    <h2 class="text-center m-5">Politics</h2>
  </div>
{% endblock  %}


{% block content %}

<section class="row" id="latest">
  {% for h in politics %}

  <div class="col-lg-3 col-md-4">
    <div class="card">
      <img src="/media/{{h.image}}" class="card-img-top" alt="photo">
      <div class="card-body">
        <h5 class="card-title">{{h.name}}</h5>
        
        <p class="card-text">{{h.time}}</p>
        <a href="{{h.id}}" class="btn btn-primary">Click Here
          
        </a>
       

        {% comment %} <button class="btn btn-outline-primary like-btn" data-article-id="{{ h.id }}"> {% endcomment %}
          {% comment %} <i class="far fa-heart"></i>
          <span class="like-count">{{ h.like_set.count }}</span>
      </button>
       {% endcomment %}
      
      <script src="script.js">
      </script>
      </div>
    </div>
  </div>


{% endfor %}
{% endblock  %}

templates/sports.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<div class="col-12">
    <h2 class="text-center m-5">Sports</h2>
  </div>

{% endblock  %}



{% block content %}

<section class="row" id="latest">
  {% for h in sports %}

  <div class="col-lg-3 col-md-4">
    <div class="card">
      <img src="/media/{{h.image}}" class="card-img-top" alt="photo">
      <div class="card-body">
        <h5 class="card-title">{{h.name}}</h5>
        
        <p class="card-text">{{h.time}}</p>
        <a href="{{h.id}}" class="btn btn-primary">Click Here
          
        </a>

        <button class="btn btn-outline-primary like-btn" data-article-id="{{ article.id }}">
          <i class="far fa-heart"></i>
          <span class="like-count">{{ article.like_set.count }}</span>
      </button>
    
      
      <script src="script.js">
      </script>
      </div>
    </div>
  </div>


{% endfor %}
{% endblock  %}